### ISSUE TITLE
Sửa câu trả lời bài tập 3!

### ISSUE THREAD

**Issue by VinhDevNguyen** [VinhDevNguyen/Machine-Learning#8]
https://github.com/VinhDevNguyen/Machine-Learning/blob/6baacb9f15de0678ae903814551f379fc458c443/LAB05/LAB05.py#L61

**Comment by VinhDevNguyen** [comment]
Coi lại câu 1 và câu 2

**Comment by dxv2k** [comment]
# Câu 2
Ý tưởng của kernel là thay vì ánh xạ một cách cụ thể từng phương trình hồi quy tuyến tính để tạo bộ phân lớp thì ở đây t có thể sử dụng kernel một cách cụ thể 
[Instead of explicit mapping for each class (multiple classifiers) with linear regression, we can use the kernel to do it]
