### ISSUE TITLE
Help Bài Tập 5

### ISSUE THREAD

**Issue by VinhDevNguyen** [VinhDevNguyen/Machine-Learning#9]
https://github.com/VinhDevNguyen/Machine-Learning/blob/9e5f3b7b89797e0495b0bfac42da8952463aa152/LAB05/LAB05.py#L65
Nên tăng hay giảm tham số $\gamma$ và C

**Comment by VinhDevNguyen** [comment]
- <ins>Yêu cầu</ins>: Giả sử bạn dùng bộ phân loại ``SVM`` với hàm ``kernel`` (radial basis function) ``RBF`` cho tập huấn luyện và thấy mô hình phân loại chưa tốt. Để cải thiện, bạn sẽ giảm hay tăng tham số $\gamma$ trong công thức hàm ``kernel``, tham số ``C`` trong hàm mất mát.

**Comment by dxv2k** [comment]
> * Yêu cầu: Giả sử bạn dùng bộ phân loại `SVM` với hàm `kernel` (radial basis function) `RBF` cho tập huấn luyện và thấy mô hình phân loại chưa tốt. Để cải thiện, bạn sẽ giảm hay tăng tham số $\gamma$ trong công thức hàm `kernel`, tham số `C` trong hàm mất mát.

Thông thường cả ta sẽ cố gắng tăng cả 2 tham số cùng lúc. Đối với tham gamma, kernel sẽ cố gắng fit dataset nhưng đối với tham số C thì ta lại "phạt". Vì thế ta cần phải tìm điểm cân bằng giữa tham số C và gamma cùng một lúc

**Comment by VinhDevNguyen** [comment]
@dxv2k 
Theo tao thấy thì chúng ta phải random (tăng hoặc giảm cả hai tham số) đến khi nào tìm được kết quả tốt nhất. Giống cái hàm mình dùng để tìm `gamma` và `C` trong bài tập 6
```python
param_distributions = {"gamma": reciprocal(0.001, 0.1), "C": uniform(1, 10)}
rnd_search_cv = RandomizedSearchCV(svm_clf, param_distributions, n_iter=10, verbose=2, cv=3)
rnd_search_cv.fit(X_train_scaled[:1000], y_train[:1000])
```

**Comment by dxv2k** [comment]
M vào scikit learn đọc ấy, nó có plot sẵn đồ thị theo C với gamma. 
C penalty
Gamma thì cố gắng fit
Nên phải tìm điểm cân bằng

**Comment by VinhDevNguyen** [comment]
Vậy thì mình phải tìm `gamma` và `C` cho hợp lí để tìm ra được kết quả tốt nhất đúng không ông @dxv2k ?

**Comment by dxv2k** [comment]
Ừa đúng rồi, nên có nhiều cách để tìm, random luôn cũng được

**Comment by VinhDevNguyen** [comment]
Okie vậy tóm lại tao sẽ ghi là 
```
Đối với tham số `gamma`, kernel sẽ cố gắng fit dataset nhưng đối với tham số `C` thì ta lại "phạt". Vì thế ta cần phải tìm điểm cân bằng giữa tham số C và gamma cùng một lúc bằng cách tăng hoặc là giảm để tìm ra được giá trị tốt nhất giúp mô hình hoạt động tốt hơn.
```
Mày thấy thế nào @dxv2k ?

**Comment by dxv2k** [comment]
Ừa vậy được rồi đó

**Comment by VinhDevNguyen** [comment]
Done! Nếu thiếu sót gì thì re-open issue này sau.
